name: Deploy

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Build and push backend Docker image
      run: |
        cd backend
        docker build -t lvlhub-backend .
        docker tag lvlhub-backend:latest ${{ secrets.AWS_ECR_REGISTRY }}/lvlhub-backend:latest
        docker push ${{ secrets.AWS_ECR_REGISTRY }}/lvlhub-backend:latest
    
    - name: Build and push frontend Docker image
      run: |
        cd frontend
        docker build -t lvlhub-frontend .
        docker tag lvlhub-frontend:latest ${{ secrets.AWS_ECR_REGISTRY }}/lvlhub-frontend:latest
        docker push ${{ secrets.AWS_ECR_REGISTRY }}/lvlhub-frontend:latest
    
    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster lvlhub-cluster --service lvlhub-backend --force-new-deployment
        aws ecs update-service --cluster lvlhub-cluster --service lvlhub-frontend --force-new-deployment 